AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  documents-set-textract
Globals:
  Function:
    Runtime: nodejs8.10
    Timeout: 180
    Handler: app.lambdaHandler
    Environment:
      Variables:
        ImagesBucket: !Ref ImagesBucket
        TextractBucket: !Ref TextractBucket
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

  ConvertPdfToImages:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: pdf2images/
      Timeout: 900
      MemorySize: 1024
      Policies: AWSLambdaExecute
      Layers:
        - !Ref GhostscriptLayer
      Events:
        ConvertPdfToImagesEvent:
          Type: S3
          Properties:
            Bucket: !Ref PdfBucket
            Events: s3:ObjectCreated:*

  GhostscriptLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers/lambda-ghostscript.zip
      CompatibleRuntimes:
        - nodejs8.10
      LicenseInfo: 'Available under the MIT-0 license.'
      RetentionPolicy: Delete    
      
  PdfBucket:
    Type: AWS::S3::Bucket
    
  ImagesBucket:
    Type: AWS::S3::Bucket
  
  TextractBucket:
    Type: AWS::S3::Bucket
    
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
